version: "3.9"
services:
  chatgptslackbot:
    build:
      context: .
    image: chatgptslackbot
    restart: always
    container_name: chatgptslackbot
    env_file:
      - ./variables.env
    volumes:
      - ./app.py:/app/app.py 
    ports:
      - "4000:4000"
